// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// build_barcode_dict_cpp
List build_barcode_dict_cpp(CharacterVector barcodes, CharacterVector names, int max_barcode_edit);
RcppExport SEXP _miaoseq_build_barcode_dict_cpp(SEXP barcodesSEXP, SEXP namesSEXP, SEXP max_barcode_editSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type names(namesSEXP);
    Rcpp::traits::input_parameter< int >::type max_barcode_edit(max_barcode_editSEXP);
    rcpp_result_gen = Rcpp::wrap(build_barcode_dict_cpp(barcodes, names, max_barcode_edit));
    return rcpp_result_gen;
END_RCPP
}
// demux_reads_cpp
List demux_reads_cpp(CharacterVector seqs, CharacterVector ids, std::string f_suffix, std::string r_suffix, std::string f_prefix, std::string r_prefix, CharacterVector f_barcodes, CharacterVector f_barcode_names, CharacterVector r_barcodes, CharacterVector r_barcode_names, CharacterVector pair_f_names, CharacterVector pair_r_names, CharacterVector pair_ids, CharacterVector sample_ids, int end_window, int max_anchor_edit, int max_prefix_edit, int max_barcode_edit, bool require_prefix, bool check_prefix, bool allow_revcomp, int n_core);
RcppExport SEXP _miaoseq_demux_reads_cpp(SEXP seqsSEXP, SEXP idsSEXP, SEXP f_suffixSEXP, SEXP r_suffixSEXP, SEXP f_prefixSEXP, SEXP r_prefixSEXP, SEXP f_barcodesSEXP, SEXP f_barcode_namesSEXP, SEXP r_barcodesSEXP, SEXP r_barcode_namesSEXP, SEXP pair_f_namesSEXP, SEXP pair_r_namesSEXP, SEXP pair_idsSEXP, SEXP sample_idsSEXP, SEXP end_windowSEXP, SEXP max_anchor_editSEXP, SEXP max_prefix_editSEXP, SEXP max_barcode_editSEXP, SEXP require_prefixSEXP, SEXP check_prefixSEXP, SEXP allow_revcompSEXP, SEXP n_coreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type seqs(seqsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< std::string >::type f_suffix(f_suffixSEXP);
    Rcpp::traits::input_parameter< std::string >::type r_suffix(r_suffixSEXP);
    Rcpp::traits::input_parameter< std::string >::type f_prefix(f_prefixSEXP);
    Rcpp::traits::input_parameter< std::string >::type r_prefix(r_prefixSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type f_barcodes(f_barcodesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type f_barcode_names(f_barcode_namesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type r_barcodes(r_barcodesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type r_barcode_names(r_barcode_namesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pair_f_names(pair_f_namesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pair_r_names(pair_r_namesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pair_ids(pair_idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sample_ids(sample_idsSEXP);
    Rcpp::traits::input_parameter< int >::type end_window(end_windowSEXP);
    Rcpp::traits::input_parameter< int >::type max_anchor_edit(max_anchor_editSEXP);
    Rcpp::traits::input_parameter< int >::type max_prefix_edit(max_prefix_editSEXP);
    Rcpp::traits::input_parameter< int >::type max_barcode_edit(max_barcode_editSEXP);
    Rcpp::traits::input_parameter< bool >::type require_prefix(require_prefixSEXP);
    Rcpp::traits::input_parameter< bool >::type check_prefix(check_prefixSEXP);
    Rcpp::traits::input_parameter< bool >::type allow_revcomp(allow_revcompSEXP);
    Rcpp::traits::input_parameter< int >::type n_core(n_coreSEXP);
    rcpp_result_gen = Rcpp::wrap(demux_reads_cpp(seqs, ids, f_suffix, r_suffix, f_prefix, r_prefix, f_barcodes, f_barcode_names, r_barcodes, r_barcode_names, pair_f_names, pair_r_names, pair_ids, sample_ids, end_window, max_anchor_edit, max_prefix_edit, max_barcode_edit, require_prefix, check_prefix, allow_revcomp, n_core));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_miaoseq_build_barcode_dict_cpp", (DL_FUNC) &_miaoseq_build_barcode_dict_cpp, 3},
    {"_miaoseq_demux_reads_cpp", (DL_FUNC) &_miaoseq_demux_reads_cpp, 22},
    {NULL, NULL, 0}
};

RcppExport void R_init_miaoseq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
