# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Trim reads to the amplicon span defined by primer pairs (C++)
#'
#' Returns a list with trimmed `seq`, and 0-based half-open
#' coordinates `start` / `end` (NA when trim fails).
#'
#' When `include_primers` is `FALSE` (default), the span is the insert
#' between primers. When `TRUE`, the span includes both primer matches
#' (F start through R end), so only outer adapters are removed.
#'
#' @keywords internal
#' @noRd
trim_amplicon_insert_cpp <- function(seqs, f_primer, r_primer, max_edit = 5L, n_core = 1L, include_primers = FALSE) {
    .Call(`_miaoseq_trim_amplicon_insert_cpp`, seqs, f_primer, r_primer, max_edit, n_core, include_primers)
}

#' Find best primer hit in a sequence window (C++)
#' @keywords internal
#' @noRd
find_primer_hit_cpp <- function(window, primer, max_edit = 3L) {
    .Call(`_miaoseq_find_primer_hit_cpp`, window, primer, max_edit)
}

#' Edit distance with edlib NW (C++)
#' @keywords internal
#' @noRd
edlib_edit_distance_cpp <- function(query, target, max_edit = 8L) {
    .Call(`_miaoseq_edlib_edit_distance_cpp`, query, target, max_edit)
}

#' Assign genes by primer pairs across reads (C++)
#' @keywords internal
#' @noRd
assign_genes_primers_cpp <- function(seqs, gene_ids, f_primers, r_primers, end_window = 80L, max_primer_edit = 3L, n_core = 1L) {
    .Call(`_miaoseq_assign_genes_primers_cpp`, seqs, gene_ids, f_primers, r_primers, end_window, max_primer_edit, n_core)
}

#' Majority consensus for a set of sequences (C++)
#' @keywords internal
#' @noRd
consensus_sequences_cpp <- function(seqs, max_edit = 8L) {
    .Call(`_miaoseq_consensus_sequences_cpp`, seqs, max_edit)
}

#' Quality-weighted consensus (Phred) for a set of sequences (C++)
#' @keywords internal
#' @noRd
consensus_sequences_quality_cpp <- function(seqs, quals, max_edit = 8L) {
    .Call(`_miaoseq_consensus_sequences_quality_cpp`, seqs, quals, max_edit)
}

#' Assign genes by amplicon reference edit distance (C++)
#' @keywords internal
#' @noRd
assign_genes_amplicon_ref_cpp <- function(seqs, ref_ids, ref_seqs, max_edit = 12L, n_core = 1L) {
    .Call(`_miaoseq_assign_genes_amplicon_ref_cpp`, seqs, ref_ids, ref_seqs, max_edit, n_core)
}

#' Greedy cluster + consensus for one gene bucket (C++)
#' @keywords internal
#' @noRd
cluster_consensus_gene_cpp <- function(seqs, sample_id, gene_id, method = "both", min_cluster_reads = 5L, max_clusters = 20L, max_edit = 12L, quals = NULL, consensus_backend = "majority") {
    .Call(`_miaoseq_cluster_consensus_gene_cpp`, seqs, sample_id, gene_id, method, min_cluster_reads, max_clusters, max_edit, quals, consensus_backend)
}

#' Bucket FASTQ reads by demultiplex assignments (C++)
#'
#' Streams one or more FASTQ files with a buffered reader and returns
#' per-sample `read_id` / `seq` / `qual` character vectors for target samples.
#'
#' @keywords internal
#' @noRd
bucket_fastq_assignments_cpp <- function(fastq_files, read_ids, sample_ids, target_samples) {
    .Call(`_miaoseq_bucket_fastq_assignments_cpp`, fastq_files, read_ids, sample_ids, target_samples)
}

#' Read all FASTQ records into id/seq/qual vectors (C++)
#' @keywords internal
#' @noRd
read_fastq_seqs_cpp <- function(fastq) {
    .Call(`_miaoseq_read_fastq_seqs_cpp`, fastq)
}

#' Reverse-complement sequences optionally per-read (C++)
#' @keywords internal
#' @noRd
reverse_complement_seqs_cpp <- function(seqs, flip) {
    .Call(`_miaoseq_reverse_complement_seqs_cpp`, seqs, flip)
}

#' Reverse quality strings optionally per-read (C++)
#' @keywords internal
#' @noRd
reverse_quals_cpp <- function(quals, flip) {
    .Call(`_miaoseq_reverse_quals_cpp`, quals, flip)
}

#' Build barcode mutant dictionary (C++)
#' @keywords internal
#' @noRd
build_barcode_dict_cpp <- function(barcodes, names, max_barcode_edit = 2L) {
    .Call(`_miaoseq_build_barcode_dict_cpp`, barcodes, names, max_barcode_edit)
}

#' Demultiplex reads with C++ edlib core
#' @keywords internal
#' @noRd
demux_reads_cpp <- function(seqs, ids, f_suffix, r_suffix, f_barcodes, f_barcode_names, r_barcodes, r_barcode_names, pair_f_names, pair_r_names, pair_ids, sample_ids, end_window = 120L, max_anchor_edit = 10L, max_barcode_edit = 2L, allow_revcomp = TRUE, allow_single_end = FALSE, n_core = 1L) {
    .Call(`_miaoseq_demux_reads_cpp`, seqs, ids, f_suffix, r_suffix, f_barcodes, f_barcode_names, r_barcodes, r_barcode_names, pair_f_names, pair_r_names, pair_ids, sample_ids, end_window, max_anchor_edit, max_barcode_edit, allow_revcomp, allow_single_end, n_core)
}

#' Stream-demultiplex FASTQ files; write TSV (+ optional per-sample FASTQ)
#'
#' Reads FASTQ in chunks, demultiplexes with OpenMP, and streams
#' `assignments.tsv` / `unassigned.tsv`. When `split_reads` is TRUE, also
#' writes per-sample FASTQ in the same pass.
#'
#' @keywords internal
#' @noRd
demux_fastq_stream_cpp <- function(fastq_files, demult_dir, f_suffix, r_suffix, f_barcodes, f_barcode_names, r_barcodes, r_barcode_names, pair_f_names, pair_r_names, pair_ids, sample_ids, end_window = 120L, max_anchor_edit = 10L, max_barcode_edit = 2L, allow_revcomp = TRUE, allow_single_end = FALSE, n_core = 1L, chunk_size = 20000L, split_reads = FALSE, compress = TRUE, include_unassigned_fastq = FALSE) {
    .Call(`_miaoseq_demux_fastq_stream_cpp`, fastq_files, demult_dir, f_suffix, r_suffix, f_barcodes, f_barcode_names, r_barcodes, r_barcode_names, pair_f_names, pair_r_names, pair_ids, sample_ids, end_window, max_anchor_edit, max_barcode_edit, allow_revcomp, allow_single_end, n_core, chunk_size, split_reads, compress, include_unassigned_fastq)
}

#' Split FASTQ by assignments TSV (C++ streaming)
#' @keywords internal
#' @noRd
split_fastq_by_assignment_cpp <- function(fastq_files, assignments_tsv, out_dir, compress = TRUE, include_unassigned = FALSE, unassigned_tsv = "") {
    .Call(`_miaoseq_split_fastq_by_assignment_cpp`, fastq_files, assignments_tsv, out_dir, compress, include_unassigned, unassigned_tsv)
}

#' Global NW gapped alignment via edlib (query vs target/ref).
#' @keywords internal
#' @noRd
edlib_nw_align_cpp <- function(query, target) {
    .Call(`_miaoseq_edlib_nw_align_cpp`, query, target)
}

#' Map ungapped ref coordinates to gapped alignment bounds (1-based inclusive).
#' @keywords internal
#' @noRd
gapped_window_bounds_cpp <- function(ref_aln, start_ungapped, end_ungapped) {
    .Call(`_miaoseq_gapped_window_bounds_cpp`, ref_aln, start_ungapped, end_ungapped)
}

#' Adaptive edit-window extraction (C++ port of the R helper).
#' @keywords internal
#' @noRd
extract_adaptive_edit_window_cpp <- function(ref_aln, query_aln, start, end, anchor_bp = 5L, max_expand = 50L) {
    .Call(`_miaoseq_extract_adaptive_edit_window_cpp`, ref_aln, query_aln, start, end, anchor_bp, max_expand)
}

#' Per-read editcall extraction (trim assumed done): align + windows + joint.
#' @keywords internal
#' @noRd
editcall_process_reads_cpp <- function(sample_id, index_pair_id, read_id, gene_id, seqs, pam_gene, pam_target_gene, pam_guide_id, pam_cut_insert, pam_win_start, pam_win_end, ref_gene_id, ref_seq, check_window = 10L, anchor_bp = 5L, max_expand = 50L, min_span_bp = 30L, excision_tol_bp = 20L, n_core = 1L) {
    .Call(`_miaoseq_editcall_process_reads_cpp`, sample_id, index_pair_id, read_id, gene_id, seqs, pam_gene, pam_target_gene, pam_guide_id, pam_cut_insert, pam_win_start, pam_win_end, ref_gene_id, ref_seq, check_window, anchor_bp, max_expand, min_span_bp, excision_tol_bp, n_core)
}

