# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build barcode mutant dictionary (C++)
#' @keywords internal
#' @noRd
build_barcode_dict_cpp <- function(barcodes, names, max_barcode_edit = 2L) {
    .Call(`_miaoseq_build_barcode_dict_cpp`, barcodes, names, max_barcode_edit)
}

#' Demultiplex reads with C++ edlib core
#' @keywords internal
#' @noRd
demux_reads_cpp <- function(seqs, ids, f_suffix, r_suffix, f_prefix, r_prefix, f_barcodes, f_barcode_names, r_barcodes, r_barcode_names, pair_f_names, pair_r_names, pair_ids, sample_ids, end_window = 120L, max_anchor_edit = 10L, max_prefix_edit = 5L, max_barcode_edit = 2L, require_prefix = FALSE, check_prefix = FALSE, allow_revcomp = TRUE, n_core = 1L) {
    .Call(`_miaoseq_demux_reads_cpp`, seqs, ids, f_suffix, r_suffix, f_prefix, r_prefix, f_barcodes, f_barcode_names, r_barcodes, r_barcode_names, pair_f_names, pair_r_names, pair_ids, sample_ids, end_window, max_anchor_edit, max_prefix_edit, max_barcode_edit, require_prefix, check_prefix, allow_revcomp, n_core)
}

